"""The agent skill, generated from the command registry.

An agent needs to be told what DPlanner is and what it can do. Writing that down by hand
would mean writing every command twice, and the copy would be wrong within a month — a skill
that describes a flag which no longer exists is worse than no skill, because it is believed.

So the skill is a **projection of the registry**: the hand-written part is the part a
registry cannot know (what a product is, how to work with the user), and everything else —
the command list, each command's arguments, the aspects — is rendered from the same objects
``dplanner --help`` renders. It cannot describe a command that does not exist.

**The output is a pure function of the registry.** Argparse wraps help text to the terminal's
width, so the same command run in two windows would produce two different files; the parsers
are built at a fixed width instead. The generated files go into version control, and a diff
that depends on who ran it is a diff nobody reads.
"""

import contextlib
import shlex
import shutil
from collections.abc import Sequence
from pathlib import Path

from dplanner.cli.command import CliCommand, CliRegistry
from dplanner.cli.main import PROG, build_tree
from dplanner.domain.aspects import AspectSpec
from dplanner.domain.model import EDGE_KINDS
from dplanner.identity import APP_NAME, APP_VERSION

SKILL_DIR = ".claude/skills/dplanner"
SKILL_FILE = "SKILL.md"
REFERENCE_FILE = "reference.md"

DESCRIPTION = (
    "Plan software work as a product of projects, each a graph of steps carrying "
    "estimates, tickets, descriptions and GitHub branch/PR refs. Use when asked to plan, "
    "break down or estimate development work, or when a DPlanner product is present."
)


def preamble() -> str:
    return (Path(__file__).parent / "skill_preamble.md").read_text()


def generate(registry: CliRegistry, aspects: Sequence[AspectSpec]) -> dict[str, str]:
    """The skill, as filenames to content. Two files, because they are read differently.

    ``SKILL.md`` is what an agent reads first and has to be short enough to hold in mind.
    ``reference.md`` is every argument of every command, which is a lookup, not a read.
    """
    return {
        SKILL_FILE: _skill(registry, aspects),
        REFERENCE_FILE: _reference(registry),
    }


def _skill(registry: CliRegistry, aspects: Sequence[AspectSpec]) -> str:
    lines = [
        "---",
        f"name: {PROG}",
        f"description: {DESCRIPTION}",
        "---",
        "",
        f"# {APP_NAME}",
        "",
        preamble().rstrip(),
        "",
        "## Where the product is",
        "",
        "Commands find the product by walking **up from the working directory** looking for",
        "`product.json`. If you are already inside the product's checkout and the plan lives",
        "there, nothing needs configuring. Otherwise pass `--workspace PATH`, or set",
        "`$DPLANNER_WORKSPACE`.",
        "",
        "## Commands",
        "",
    ]
    for noun, commands in registry.groups().items():
        lines.append(f"### `{PROG} {noun}`")
        lines.append("")
        for command in commands:
            lines.append(f"- `{PROG} {command.id}` — {command.summary}")
        lines.append("")
    lines += [
        f"Every argument of every command is in [{REFERENCE_FILE}]({REFERENCE_FILE}).",
        "",
        "## Aspects a step can carry",
        "",
    ]
    for aspect in aspects:
        lines.append(f"- **{aspect.label}** (`{aspect.id}`) — {aspect.summary}")
    lines += [
        "",
        "## Edge kinds",
        "",
    ]
    for kind, orders in sorted(EDGE_KINDS.items()):
        meaning = "orders the graph; cycles are refused" if orders else "a plain link"
        lines.append(f"- `{kind}` — {meaning}")
    lines += ["", f"<!-- generated by {PROG} {APP_VERSION}; edits are overwritten -->", ""]
    return "\n".join(lines)


def _reference(registry: CliRegistry) -> str:
    _parser, verb_parsers = build_tree(registry)
    lines = [
        f"# {PROG} reference",
        "",
        f"Generated from {APP_NAME}'s command registry. Every command, every argument.",
        "",
    ]
    for command in registry.commands():
        lines += [f"## `{PROG} {command.id}`", "", command.summary, "", "```"]
        # The parser's own help, examples included: one rendering, so the reference and
        # `--help` cannot come to disagree.
        lines.append(verb_parsers[command.id].format_help().rstrip())
        lines.append("```")
        lines.append("")
    lines.append(f"<!-- generated by {PROG} {APP_VERSION}; edits are overwritten -->")
    lines.append("")
    return "\n".join(lines)


# -- installing ---------------------------------------------------------------------------------


def target_dir(*, user: bool, here: Path | None = None) -> Path:
    """Where the skill goes: this user's home, or the directory being worked in."""
    base = Path.home() if user else (here or Path.cwd())
    return base / SKILL_DIR


def install_command() -> list[str]:
    """The command that puts ``dplanner`` on PATH, as argv.

    From a source checkout that is an editable tool install, which tracks the checkout
    instead of freezing a copy.
    """
    root = Path(__file__).resolve().parents[3]
    if (root / "pyproject.toml").is_file():
        return ["uv", "tool", "install", "--editable", str(root)]
    return ["uv", "tool", "install", PROG]


def uninstall_command() -> list[str]:
    """The command that takes the installed ``dplanner`` tool back out, as argv."""
    return ["uv", "tool", "uninstall", PROG]


def path_hint() -> str | None:
    """None when ``dplanner`` resolves on PATH; otherwise the command that puts it there.

    The skill tells agents to run ``dplanner``, so a machine where that command does not
    resolve has half an install.
    """
    if shutil.which(PROG) is not None:
        return None
    return shlex.join(install_command())


def worktree_warning(root: Path | None = None) -> str | None:
    """A caution when the editable install would track a git worktree, else None.

    A worktree is often temporary — a branch's scratch checkout — and an editable install
    pointing into one breaks the moment the worktree is removed. The warning names the main
    checkout when the worktree's ``.git`` file says where it is.
    """
    if root is None:
        root = Path(__file__).resolve().parents[3]
    gitfile = root / ".git"
    if not gitfile.is_file():  # A directory means a main checkout; a file marks a worktree.
        return None
    message = (
        f"This build runs from a git worktree ({root}) — the installed command would "
        "break when the worktree is removed."
    )
    content = gitfile.read_text().strip()
    if content.startswith("gitdir:"):
        gitdir = Path(content.removeprefix("gitdir:").strip())
        # A linked worktree's gitdir is <main>/.git/worktrees/<name>.
        if gitdir.parent.name == "worktrees" and gitdir.parents[1].name == ".git":
            main = gitdir.parents[2]
            message += (
                f" Consider installing from the main checkout:  uv tool install --editable {main}"
            )
    return message


def status(files: dict[str, str], directory: Path) -> str:
    """``installed``, ``stale`` or ``missing`` — what an "Update…" label reads from."""
    for name, content in files.items():
        path = directory / name
        if not path.is_file():
            return "missing"
        if path.read_text() != content:
            return "stale"
    return "installed"


def install(files: dict[str, str], directory: Path) -> list[Path]:
    directory.mkdir(parents=True, exist_ok=True)
    written = []
    for name, content in sorted(files.items()):
        path = directory / name
        path.write_text(content)
        written.append(path)
    return written


def uninstall(files: dict[str, str], directory: Path) -> list[Path]:
    """Remove exactly the files install would write — never anything the user added.

    The directory goes too once it is empty; a directory holding somebody's own files
    survives.
    """
    removed = []
    for name in sorted(files):
        path = directory / name
        if path.is_file():
            path.unlink()
            removed.append(path)
    with contextlib.suppress(OSError):
        directory.rmdir()
    return removed


def commands(aspects: Sequence[AspectSpec], registry: CliRegistry) -> list[CliCommand]:
    """The skill verbs: show, install, uninstall, status.

    They take the registry they describe, which is the same registry they are registered
    into — the composition root closes the loop, and nothing here has to go looking.
    """
    from argparse import ArgumentParser, Namespace

    from dplanner.cli.command import CliContext

    def files() -> dict[str, str]:
        return generate(registry, aspects)

    def show(context: CliContext, _args: Namespace) -> int:
        context.report(files(), files()[SKILL_FILE])
        return 0

    def configure(parser: ArgumentParser) -> None:
        where = parser.add_mutually_exclusive_group()
        where.add_argument(
            "--user",
            action="store_true",
            help=f"install into ~/{SKILL_DIR} (the default)",
        )
        where.add_argument(
            "--project",
            action="store_true",
            help=f"install into ./{SKILL_DIR}, so it travels with the repository",
        )

    def where(args: Namespace) -> Path:
        return target_dir(user=not args.project)

    def do_install(context: CliContext, args: Namespace) -> int:
        written = install(files(), where(args))
        context.report(
            {"installed": [str(path) for path in written]},
            "\n".join(str(path) for path in written),
        )
        return 0

    def do_uninstall(context: CliContext, args: Namespace) -> int:
        removed = uninstall(files(), where(args))
        context.report(
            {"removed": [str(path) for path in removed]},
            "\n".join(str(path) for path in removed) if removed else "nothing installed",
        )
        return 0

    def do_status(context: CliContext, args: Namespace) -> int:
        directory = where(args)
        state = status(files(), directory)
        hint = path_hint()
        text = f"{state}  {directory}"
        if hint is not None:
            text += f"\ndplanner is not on PATH — fix with: {hint}"
        context.report(
            {"status": state, "directory": str(directory), "cli_on_path": hint is None},
            text,
        )
        return 0

    return [
        CliCommand(
            path=("skill", "show"),
            summary="Print the agent skill for this build, without installing it.",
            run=show,
            needs_workspace=False,
            examples=(f"{PROG} skill show",),
        ),
        CliCommand(
            path=("skill", "install"),
            summary="Write the agent skill so a coding agent can find it.",
            configure=configure,
            run=do_install,
            needs_workspace=False,
            examples=(f"{PROG} skill install", f"{PROG} skill install --project"),
        ),
        CliCommand(
            path=("skill", "uninstall"),
            summary="Remove the installed agent skill.",
            configure=configure,
            run=do_uninstall,
            needs_workspace=False,
            examples=(f"{PROG} skill uninstall",),
        ),
        CliCommand(
            path=("skill", "status"),
            summary="Whether the installed skill matches this build.",
            configure=configure,
            run=do_status,
            needs_workspace=False,
            examples=(f"{PROG} skill status",),
        ),
    ]
